# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.1
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _libCars
else:
    import _libCars

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


autos = _libCars.autos
camion = _libCars.camion
bus = _libCars.bus
ambulancia = _libCars.ambulancia
class Vehiculo(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _libCars.Vehiculo_swiginit(self, _libCars.new_Vehiculo(*args))
    __swig_destroy__ = _libCars.delete_Vehiculo

    def getLargo(self):
        return _libCars.Vehiculo_getLargo(self)

    def getPeso(self):
        return _libCars.Vehiculo_getPeso(self)

    def getTipo(self):
        return _libCars.Vehiculo_getTipo(self)

# Register Vehiculo in _libCars:
_libCars.Vehiculo_swigregister(Vehiculo)

class Transbordador(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, *args):
        _libCars.Transbordador_swiginit(self, _libCars.new_Transbordador(*args))
    __swig_destroy__ = _libCars.delete_Transbordador

    def pushVehiculo(self, fila, v):
        return _libCars.Transbordador_pushVehiculo(self, fila, v)

    def popVehiculo(self, fila):
        return _libCars.Transbordador_popVehiculo(self, fila)

    def getEspacioLibre(self, fila):
        return _libCars.Transbordador_getEspacioLibre(self, fila)

    def getLargoFila(self, fila):
        return _libCars.Transbordador_getLargoFila(self, fila)

    def getPesoLibre(self):
        return _libCars.Transbordador_getPesoLibre(self)

    def getTipo(self, tipo):
        return _libCars.Transbordador_getTipo(self, tipo)

# Register Transbordador in _libCars:
_libCars.Transbordador_swigregister(Transbordador)



